let TileSet = { "columns":0,
 "grid":
    {
     "height":1,
     "orientation":"orthogonal",
     "width":1
    },
 "margin":0,
 "name":"Killian TileSet",
 "spacing":0,
 "tilecount":6,
 "tiledversion":"1.7.2",
 "tileheight":128,
 "tiles":[
        {
         "id":0,
         "image":"sprites\/terrain\/dirt.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":1,
         "image":"sprites\/terrain\/dirt_wall.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":2,
         "image":"sprites\/terrain\/dirt_wall_top.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":3,
         "image":"sprites\/terrain\/grass_1.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":4,
         "image":"sprites\/terrain\/grass_2.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":5,
         "image":"sprites\/terrain\/grass_3.png",
         "imageheight":128,
         "imagewidth":128
        }],
 "tilewidth":128,
 "type":"tileset",
 "version":"1.6"
}