{ "columns":0,
 "grid":
    {
     "height":1,
     "orientation":"orthogonal",
     "width":1
    },
 "margin":0,
 "name":"KillianTileSetV2",
 "spacing":0,
 "tilecount":37,
 "tiledversion":"1.7.2",
 "tileheight":256,
 "tiles":[
        {
         "id":0,
         "image":"..\/sprites\/terrain\/grass_1.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":1,
         "image":"..\/sprites\/terrain\/grass_2.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":2,
         "image":"..\/sprites\/terrain\/grass_3.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":3,
         "image":"..\/sprites\/terrain\/dirt.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":4,
         "image":"..\/sprites\/terrain\/dirt_1_horizontal.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":5,
         "image":"..\/sprites\/terrain\/dirt_2_horizontal.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":6,
         "image":"..\/sprites\/terrain\/dirt_1_vertical.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":7,
         "image":"..\/sprites\/terrain\/dirt_2_vertical.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":8,
         "image":"..\/sprites\/terrain\/dirt_wall.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":12,
         "image":"..\/sprites\/terrain\/dirt_wall_bottom.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":13,
         "image":"..\/sprites\/terrain\/dirt_wall_bottom_left_full.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":14,
         "image":"..\/sprites\/terrain\/dirt_wall_bottom_right_full.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":15,
         "image":"..\/sprites\/terrain\/dirt_wall_left.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":16,
         "image":"..\/sprites\/terrain\/dirt_wall_right.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":17,
         "image":"..\/sprites\/terrain\/dirt_wall_top.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":18,
         "image":"..\/sprites\/terrain\/dirt_wall_top_left_full.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":19,
         "image":"..\/sprites\/terrain\/dirt_wall_top_right_full.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":21,
         "image":"..\/sprites\/terrain\/rock_wall_bottom.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":22,
         "image":"..\/sprites\/terrain\/rock_wall_bottom_left_full.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":23,
         "image":"..\/sprites\/terrain\/rock_wall_bottom_right_full.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":24,
         "image":"..\/sprites\/terrain\/rock_wall_left.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":25,
         "image":"..\/sprites\/terrain\/rock_wall_right.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":26,
         "image":"..\/sprites\/terrain\/rock_wall_top.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":27,
         "image":"..\/sprites\/terrain\/rock_wall_top_left_full.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":28,
         "image":"..\/sprites\/terrain\/rock_wall_top_right_full.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":29,
         "image":"..\/sprites\/terrain\/tree_wall.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":30,
         "image":"..\/sprites\/terrain\/rock_wall.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":31,
         "image":"..\/sprites\/terrain\/tree.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":32,
         "image":"..\/sprites\/terrain\/rock.png",
         "imageheight":40,
         "imagewidth":40
        }, 
        {
         "id":33,
         "image":"..\/sprites\/terrain\/big_tree.png",
         "imageheight":256,
         "imagewidth":256
        }, 
        {
         "id":37,
         "image":"..\/sprites\/hud_display\/plasma_rifle.png",
         "imageheight":12,
         "imagewidth":19
        }, 
        {
         "id":38,
         "image":"..\/sprites\/hud_display\/shotgun.png",
         "imageheight":9,
         "imagewidth":34
        }, 
        {
         "id":39,
         "image":"..\/sprites\/hud_display\/dmr.png",
         "imageheight":13,
         "imagewidth":30
        }, 
        {
         "id":40,
         "image":"..\/sprites\/elite\/elite_idle_right.png",
         "imageheight":51,
         "imagewidth":30
        }, 
        {
         "id":41,
         "image":"..\/sprites\/grunt\/grunt_idle.png",
         "imageheight":39,
         "imagewidth":27
        }, 
        {
         "id":42,
         "image":"..\/sprites\/terrain\/rock_wall_bottom_left_corner.png",
         "imageheight":128,
         "imagewidth":128
        }, 
        {
         "id":43,
         "image":"..\/sprites\/terrain\/rock_wall_bottom_right_corner.png",
         "imageheight":128,
         "imagewidth":128
        }],
 "tilewidth":256,
 "type":"tileset",
 "version":"1.6"
}